FoodAppDjangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views as user_views
from django.contrib.auth import views as authentication_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('food/', include('food.urls')),
    path('register/', user_views.register, name='register'),
    path('login/', authentication_views.LoginView.as_view(template_name='user/login.html'), name='login'),
    path('logout/', authentication_views.LogoutView.as_view(template_name='user/logout.html'), name='logout'),
    path('profile/', user_views.profile_page, name='profile'),
]

urlpatterns += [

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food/urls.py
from django.urls import path
from food.views import  update_item, delete_item, IndexClassView, FoodDetail, ItemCreate

app_name = 'food'

urlpatterns = (
    # path('', index, name='index'),
    path('', IndexClassView.as_view(), name='index'),
    # path('<int:item_id>/', detail, name='detail'),
    path('<int:pk>/', FoodDetail.as_view(), name='detail'),
    # path('add/', create_item, name='create_item'),
    path('add/', ItemCreate.as_view(), name='create_item'),
    path('update/<int:id>/', update_item, name='update_item'),
    path('delete/<int:id>/', delete_item, name='delete_item'),
)

food/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Item(models.Model):
    item_name = models.CharField(
        max_length=200,
    )
    item_desc = models.CharField(
        max_length=200,
    )
    item_price = models.IntegerField()
    item_image = models.URLField(
        default='https://livingstonbagel.com/wp-content/uploads/2016/11/food-placeholder.jpg',
        null=True,
        blank=True,
    )
    user_name = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        default=1,
    )

    def __str__(self):
        return self.item_name

    def get_absolute_url(self):
        return reverse('food:detail', kwargs={'pk': self.pk})

users/models.py
from django.db import models
from django.contrib.auth.models import User


class Profile(models.Model):
    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
    )
    image = models.ImageField(
        default='profilepic.jpg',
        upload_to='profile_pictures',
    )
    location = models.CharField(
        max_length=100,
    )

    def __str__(self):
        return self.user.username

food/forms.py
from django import forms
from .models import Item


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        fields = '__all__'

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

food/views.py
from django.shortcuts import render, redirect
from food.forms import ItemForm
from food.models import Item
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


# def index(request):
#     item_list = Item.objects.all()
#     context = {
#         'item_list': item_list,
#     }
#     return render(request, 'food/index.html', context)


class IndexClassView(ListView):
    model = Item
    template_name = 'food/index.html'
    context_object_name = 'item_list'


# def detail(request, item_id):
#     item = Item.objects.get(id=item_id)
#     context = {
#         'item': item,
#     }
#     return render(request, 'food/detail.html', context)

class FoodDetail(DetailView):
    model = Item
    template_name = 'food/detail.html'


# def create_item(request):
#     form = ItemForm(request.POST or None)
#     context = {
#         'form': form,
#     }
#     if form.is_valid():
#         form.save()
#         return redirect('food:index')
#
#     return render(request, 'food/item-form.html', context)

class ItemCreate(CreateView):
    model = Item
    fields = ['item_name', 'item_desc', 'item_price', 'item_image']
    template_name = 'food/item-form.html'

    def form_valid(self, form):
        form.instance.user_name = self.request.user

        return super().form_valid(form)


def update_item(request, id):
    item = Item.objects.get(id=id)
    form = ItemForm(request.POST or None, instance=item)
    context = {
        'form': form,
        'item': item,
    }

    if form.is_valid():
        form.save()
        return redirect('food:index')

    return render(request, 'food/item-form.html', context)


def delete_item(request, id):
    item = Item.objects.get(id=id)
    context = {
        'item': item,
    }
    if request.method == 'POST':
        item.delete()
        return redirect('food:index')
    return render(request, 'food/item-delete.html', context)

users/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.contrib import messages
from users.forms import RegisterForm


def register(request):
    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Welcome, {username}! Your account is created!')
            return redirect('food:index')
    else:
        form = RegisterForm()
    context = {
        'form': form,
    }
    return render(request, 'user/register.html', context)


@login_required
def profile_page(request):
    return render(request, 'user/profile.html')

templates/food/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'food/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>
<body>
    <nav class="navbar navbar-dark bg-dark">
        <a href="#" class="navbar-brand">Food App</a>
        <div class="navbar">
            <a href="{% url 'food:create_item' %}" class="nav-item nav-link">Add Item</a>
            <a href="#" class="nav-item nav-link">Delete Item</a>
            <a href="#" class="nav-item nav-link">View Item</a>
            {% if user.is_authenticated %}
                <a href="{% url 'logout' %}" class="nav-item nav-link">LogOut</a>
                <a href="{% url 'profile' %} " class="nav-item nav-link">Profile</a>
            {% else %}
                <a href="{% url 'login' %}" class="nav-item nav-link">LogIn</a>
            {% endif %}
        </div>
    </nav>

    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block body %}
    {% endblock %}
</body>
</html>

templates/food/detail.html
{% extends 'food/base.html' %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block body %}
        <div class="container">
            <div class="row">
                <div class="col-md-6">
{#                    <img height="300px" src="{{ item.item_image }}" class="card"/>#}
                    <img height="300px" src="{{ object.item_image }}" class="card"/>
                </div>

                <div class="col-md-6">
{#                    <h1>{{ item.item_name }}</h1>#}
{#                    <h2>{{ item.item_desc }}</h2>#}
{#                    <h3>${{ item.item_price }}</h3>#}
                    <h1>{{ object.item_name }}</h1>
                    <h2>{{ object.item_desc }}</h2>
                    <h3>${{ object.item_price }}</h3>
                    <a href="{% url 'food:delete_item' item.id %}">Delete</a>
                </div>
            </div>
        </div>

    {% endblock %}
</body>
</html>

templates/food/index.html
{% extends 'food/base.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    {% block body %}
        {% for item in item_list %}
                  <div class="row">
                    <div class="col-md-3 offset-md-2">
                        <img class="card" height="150px" src="{{ item.item_image }}"/>
                    </div>
                    <div class="col-md-4">
                        <h3>{{ item.item_name }}</h3>
                        <h5>{{ item.item_desc }}</h5>
                        <h6>${{ item.item_price }}</h6>
                        <h6>{{ item.user_name }}</h6>
                    </div>
                    <div class="col-md-2">
                        <a href="{% url 'food:detail' item.id %}" class="btn btn-success">Details</a>
                    </div>
                  </div>
        {% endfor %}
    {% endblock %}
</body>
</html>

templates/food/item-delete.html
<form method="post">
    {% csrf_token %}
    <h2>Are you sure you want to delete {{ item.item_name }}</h2>
    <button type="submit">Confirm</button>
</form>

templates/food/item-form.html
{% extends 'food/base.html' %}
{% block body %}
        <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Add Item
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {{ form }}
                            <button class="btn-info" type="submit">Add</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/login.html
{% extends 'food/base.html' %}


{% block body %}
    <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Login
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn-info" type="submit">Login</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/user/logout.html
<h1>You have been logged out</h1>

templates/user/profile.html
<h1> {{ user.username }}</h1>
<img width="100px" height="100px" src="{{ user.profile.image.url }}"></img>

templates/user/register.html
{% extends 'food/base.html' %}
{% block body %}
        <div class="container">
        <div class="row">
            <div class="col-md-4 offset-md-4">
                <div class="card">
                    <div class="card-header text-white bg-info">
                        <div class="card-title">
                            Register
                        </div>
                    </div>
                    <div class="card-body">
                        <form method="POST">
                            {% csrf_token %}
                            {% for field in form %}
                                <div class="form-group">
                                    {{ field.name }}
                                    <br>
                                    {{ field }}
                                </div>
                            {% endfor %}
                            <button class="btn-info" type="submit">SignUp</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}